name: Build and deploy ASP.Net Core app to Azure Web App - TicketingSystem

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Build & Publish API
      - name: Publish API
        run: |
          dotnet restore TicketingSystem.API/TicketingSystem.API.csproj
          dotnet build TicketingSystem.API/TicketingSystem.API.csproj -c Release
          dotnet publish TicketingSystem.API/TicketingSystem.API.csproj -c Release -o ./output/api

      # Build & Publish Blazor
      - name: Publish Blazor
        run: |
          dotnet restore TicketingSystem.Blazor/TicketingSystem.Blazor.csproj
          dotnet build TicketingSystem.Blazor/TicketingSystem.Blazor.csproj -c Release
          dotnet publish TicketingSystem.Blazor/TicketingSystem.Blazor.csproj -c Release -o ./output/blazor

      # Upload artifacts
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: ./output

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: net-app

      - name: Login to Azure using Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy API
      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ticketingsystem-api'
          package: ./output/api

      # Deploy Blazor
      - name: Deploy Blazor to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TicketingSystem'
          package: ./output/blazor
